name: Synthetics Run
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '* */6 * * *'
jobs:
  synthetics_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'synthetics-tests'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: "SYNTHETICS_JUNIT_FILE='junit-synthetics.xml' npx @elastic/synthetics . --reporter=junit --suite-params='{\"url\": \"http://localhost:8080\"} '"
        continue-on-error: true
      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v2.4.2
        with:
          report_paths: '**/junit-*.xml'
          fail_on_failure: true
          require_tests: true
