name: Synthetics Run
on: 
  push:
  pull_request:
  schedule:
    - cron:  '*/15 * * * *'
jobs:
  synthetics_test:
    runs-on: ubuntu-latest
    steps:
      - run: cd synthetics-tests && npm install
      - run: SYNTHETICS_JUNIT_FILE='junit.xml' npx @elastic/synthetics . --reporter=junit
      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'junit.xml'
