name: Synthetics Run
on: 
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron:  '*/15 * * * *'
jobs:
  synthetics_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "synthetics-tests"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
         node-version: '14'
      - run: npm install
      - run: SYNTHETICS_JUNIT_FILE='junit.xml' npx @elastic/synthetics . --reporter=junit
      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'junit.xml'
